#pragma once

#include <OCRA/Handle.hpp>

OCRA_DECLARE_HANDLE(OCRA::Buffer);

OCRA_DECLARE_HANDLE(OCRA::Command::Buffer);
OCRA_DECLARE_HANDLE(OCRA::Command::Pool);

OCRA_DECLARE_HANDLE(OCRA::Descriptor::Pool);
OCRA_DECLARE_HANDLE(OCRA::Descriptor::Set);
OCRA_DECLARE_HANDLE(OCRA::Descriptor::SetLayout);
OCRA_DECLARE_HANDLE(OCRA::Device);

OCRA_DECLARE_HANDLE(OCRA::Fence);
OCRA_DECLARE_HANDLE(OCRA::FrameBuffer);

OCRA_DECLARE_HANDLE(OCRA::Image);
OCRA_DECLARE_HANDLE(OCRA::Image::Sampler);
OCRA_DECLARE_HANDLE(OCRA::Image::View);
OCRA_DECLARE_HANDLE(OCRA::Instance);

OCRA_DECLARE_HANDLE(OCRA::Layout);

OCRA_DECLARE_HANDLE(OCRA::Memory);

OCRA_DECLARE_HANDLE(OCRA::PhysicalDevice);
OCRA_DECLARE_HANDLE(OCRA::Pipeline);
OCRA_DECLARE_HANDLE(OCRA::Pipeline::Layout);
OCRA_DECLARE_HANDLE(OCRA::Pipeline::SetLayout);

OCRA_DECLARE_HANDLE(OCRA::QueryPool);
OCRA_DECLARE_HANDLE(OCRA::Queue);

OCRA_DECLARE_HANDLE(OCRA::RenderPass);

OCRA_DECLARE_HANDLE(OCRA::Semaphore);
OCRA_DECLARE_HANDLE(OCRA::Shader::Module);
OCRA_DECLARE_HANDLE(OCRA::Shader::Stage);
OCRA_DECLARE_HANDLE(OCRA::ShaderCompiler);
OCRA_DECLARE_HANDLE(OCRA::ShaderCompiler::Shader);
OCRA_DECLARE_HANDLE(OCRA::Surface);
OCRA_DECLARE_HANDLE(OCRA::SwapChain);
