#pragma once

/**
* This file contains every includes
*/

#include <OCRA/Allocator.hpp>
#include <OCRA/Buffer.hpp>
#include <OCRA/Device.hpp>
#include <OCRA/FrameBuffer.hpp>
#include <OCRA/Handle.hpp>
#include <OCRA/Instance.hpp>
#include <OCRA/Memory.hpp>
#include <OCRA/PhysicalDevice.hpp>
#include <OCRA/QueryPool.hpp>
#include <OCRA/RenderPass.hpp>
#include <OCRA/Queue/Queue.hpp>
#include <OCRA/Queue/Fence.hpp>
#include <OCRA/Queue/Semaphore.hpp>
#include <OCRA/Common/Blend.hpp>
#include <OCRA/Common/Compare.hpp>
#include <OCRA/Common/Extent.hpp>
#include <OCRA/Common/Extent2D.hpp>
#include <OCRA/Common/Extent3D.hpp>
#include <OCRA/Common/IndexType.hpp>
#include <OCRA/Common/Logic.hpp>
#include <OCRA/Common/Offset3D.hpp>
#include <OCRA/Common/Rect2D.hpp>
#include <OCRA/Common/Rect3D.hpp>
#include <OCRA/Common/ScissorTest.hpp>
#include <OCRA/Common/SharingMode.hpp>
#include <OCRA/Common/Stencil.hpp>
#include <OCRA/Common/Timer.hpp>
#include <OCRA/Common/Vec.hpp>
#include <OCRA/Common/Vec2.hpp>
#include <OCRA/Common/Vec3.hpp>
#include <OCRA/Common/Vec4.hpp>
#include <OCRA/Common/Vec_Boolean.hpp>
#include <OCRA/Common/Vec_Functor.hpp>
#include <OCRA/Common/Vec_Interpolation.hpp>
#include <OCRA/Common/Vec_Math.hpp>
#include <OCRA/Common/VertexType.hpp>
#include <OCRA/Command/Buffer.hpp>
#include <OCRA/Command/Draw.hpp>
#include <OCRA/Command/MemoryBarrier.hpp>
#include <OCRA/Command/Pool.hpp>
#include <OCRA/Command/Query.hpp>
#include <OCRA/Command/Scissor.hpp>
#include <OCRA/Command/ViewPort.hpp>
#include <OCRA/Descriptor/Set.hpp>
#include <OCRA/Descriptor/SetLayout.hpp>
#include <OCRA/Descriptor/Pool.hpp>
#include <OCRA/Descriptor/Type.hpp>
#include <OCRA/Image/Descriptor.hpp>
#include <OCRA/Image/Filter.hpp>
#include <OCRA/Image/Format.hpp>
#include <OCRA/Image/Image.hpp>
#include <OCRA/Image/Sampler.hpp>
#include <OCRA/Image/Usage.hpp>
#include <OCRA/Image/View.hpp>
#include <OCRA/Pipeline/ColorBlendState.hpp>
#include <OCRA/Pipeline/DepthStencilState.hpp>
#include <OCRA/Pipeline/Graphics.hpp>
#include <OCRA/Pipeline/InputAssemblyState.hpp>
#include <OCRA/Pipeline/MultisampleState.hpp>
#include <OCRA/Pipeline/Pipeline.hpp>
#include <OCRA/Pipeline/RasterizationState.hpp>
#include <OCRA/Pipeline/ShaderPipelineState.hpp>
#include <OCRA/Pipeline/TessellationState.hpp>
#include <OCRA/Pipeline/VertexInputState.hpp>
#include <OCRA/Pipeline/ViewPortState.hpp>
#include <OCRA/Primitive/Topology.hpp>
#include <OCRA/Shader/Module.hpp>
#include <OCRA/Shader/Stage.hpp>
